apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-predictor
  labels:
    app: stream-predictor
    version: V0
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: stream-predictor
        version: V0
    spec:
      containers:
      - name: stream-predictor
        image: gcr.io/my-ml-prod-env/kafka-webapp-connector:0
        args:
          - mltest
          - ridgecv
          - 0
        #jupyter/scipy-notebook
        #command:
        #  - "/bin/bash"
        #  - "-c"
        #  - "pip install pymongo && pip install kafka-python && git clone https://github.com/AurelienGalicher/my-ml-prod-kit.git && cd my-ml-prod-kit/pyscripts && ipython stream_predict.py mltest ridgecv 0"
