apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  #namespace: default
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  #selector:
  #  component: elk
  #  role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elk
      containers:
      - name: logstash
        image: mykafkaconnectregistry.azurecr.io/logstash:5.2.2
        #gcr.io/my-ml-prod-env/logstash:5.2.2_2
        #logstash:5.2.2
        #command:
        #  - "/bin/bash"
        #  - "-c"
        #  - "/usr/share/logstash/bin/logstash-plugin install logstash-input-kafka && /usr/share/logstash/bin/logstash-plugin install logstash-filter-json && /usr/share/logstash/bin/logstash -f /logstash/config/logstash.conf"
        volumeMounts:
          - name: config-volume
            mountPath: /logstash/config
        imagePullSecrets:
        - name: myregistrykey
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
      restartPolicy: Always
