apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: perf-tracking
  labels:
    app: perf-tracking
spec:
  replicas: 1
  template:
    metadata:
      name: perf-tracking
      labels:
        app: perf-tracking
    spec:
      containers:
      - name: perf-tracking
        image: mykafkaconnectregistry.azurecr.io/perf-tracking:0
        #gcr.io/my-ml-prod-env/perf-tracking:0
        args:
          - kafka:9092
          - mltest
          - mongodb://mongo:27017
          - rs0
