apiVersion: v1
kind: Pod
metadata:
  name: command-demo-1
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: gcr.io/my-ml-prod-env/perf-tracking:4
    command: ["/bin/bash","-c"] 
    args: ["while :; do echo 'Hit CTRL+C'; sleep 1; done"]
