apiVersion: batch/v1
kind: Job
metadata:
  name: perf-track
  #namespace: kafka
spec:
  template:
    metadata:
      name: perf-track
    spec:
      containers:
      - name: pref-track
        image: gcr.io/my-ml-prod-env/perf-tracking:0
        #jupyter/scipy-notebook
        args:
          - "10"
          - ridgecv
          - latest
      restartPolicy: Never
