apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: train-model-cron
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
    	template:
    		spec:
      			containers:
      			- name: train-model
        		  image: gcr.io/my-ml-prod-env/training-job:2
        		  args:
          			- "5"
          			- ridgecv
          			- latest
          		  restartPolicy: OnFailure