apiVersion: batch/v1
kind: Job
metadata:
  name: train-model
  #namespace: kafka
spec:
  template:
    metadata:
      name: train-model
    spec:
      containers:
      - name: train-model
        image: gcr.io/my-ml-prod-env/training-job:0
        #jupyter/scipy-notebook
        args:
          - "10"
          - ridgecv
          - "0"
      restartPolicy: Never