apiVersion: v1
kind: Service
metadata:
  name: prediction
  labels:
    app: prediction
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: prediction
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prediction
  labels:
    app: prediction
    version: v0
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: prediction
        version: v0
    spec:
      containers:
      - name: prediction
        image: gcr.io/my-ml-prod-env/webserviceapp:0
        env:
          - name: FLASK_APP
            value: "flaskr"
        ports:
        - containerPort: 5000
          name: flask
          protocol: TCP
        #command:
        #  - "/bin/bash"
        #  - "-c"
        #  - "pip install pymongo && pip install kafka-python && git clone https://github.com/AurelienGalicher/my-ml-prod-kit.git && cd my-ml-prod-kit/webservice && pip install -e . && flask run"
